server:
  port: 8082

app:
  host: http://localhost:${server.port}

kermoss:
  service-name: market-serviceY 
  transport:
    default-layer: kafka
    kafka:
      consumer:
         group-name: ${kermoss.service-name}       
      bootstrap-address: localhost:29092,localhost:29093,localhost:29094
#      bootstrap-address: 192.168.3.127:9092,192.168.3.128:9092,192.168.3.129:9092
            
  sources:
      pizza-shop:
           kafka: io.kermoss.topics.pizzashop
           http: http://localhost:8081/command-executor/commands
           feign: pizza-shop
  sinks:   
      market-service: 
           kafka: io.kermoss.topics.pizzashop.marketservice